<?php

namespace Explotic\PlanningBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InterventionHasStagiaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterventionHasStagiaireRepository extends EntityRepository
{
}
