<?php

namespace Explotic\PlanningBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JourRepository extends EntityRepository
{
    public function findByCalendrierAndDate($idCalendrier, $dateDebut, $dateFin)
    {
        //
        return $this->getEntityManager()
                ->createQuery('
                    Select j FROM ExploticPlanningBundle:Jour j 
                    JOIN j.calendrier c
                    WHERE c.id = :idCalendrier
                    AND j.creneauDebut >= :dateDebut
                    AND j.creneauFin <= :dateFin
                    ')
                ->setParameters(array(
                    'idCalendrier'=> $idCalendrier,
                    'dateDebut' => $dateDebut,
                    'dateFin' => $dateFin,
                    ))
                ->getResult();
    }
}
