<?php

namespace Explotic\PlanningBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MyBookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyBookingRepository extends EntityRepository
{
}
