creneaurdv:
    pattern:  /
    defaults: { _controller: "ExploticAgendaBundle:CreneauRdv:index" }

creneaurdv_show:
    pattern:  /{id}/show
    defaults: { _controller: "ExploticAgendaBundle:CreneauRdv:show" }

creneaurdv_new:
    pattern:  /new
    defaults: { _controller: "ExploticAgendaBundle:CreneauRdv:new" }

creneaurdv_create:
    pattern:  /create
    defaults: { _controller: "ExploticAgendaBundle:CreneauRdv:create" }
    requirements: { _method: post }

creneaurdv_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ExploticAgendaBundle:CreneauRdv:edit" }

creneaurdv_update:
    pattern:  /{id}/update
    defaults: { _controller: "ExploticAgendaBundle:CreneauRdv:update" }
    requirements: { _method: post }

creneaurdv_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ExploticAgendaBundle:CreneauRdv:delete" }
    requirements: { _method: post }
