transfer_reservation_rdv:
    resource: "@TransferReservationBundle/Resources/config/routing/rdv.yml"
    prefix: /rdv
transfer_reservation_creneauRdv:
    resource: "@TransferReservationBundle/Resources/config/routing/creneaurdv.yml"
    prefix:   /creneaurdv    
creneaurdv_recherche_trsp:
    pattern: /recherche/{semaine}/{annee}
    defaults: { _controller: "TransferReservationBundle:CreneauRdv:recherche"}
 