transfer_reservation_creneauRdv:
    resource: "@TransferReservationBundle/Resources/config/routing/creneaurdv.yml"
    prefix:   /creneaurdv
transfer_reservation_creneauModele:
    resource: "@TransferReservationBundle/Resources/config/routing/creneaumodele.yml"
    prefix:   /creneaumodele
transfer_reservation_creneauModeleGen:
    resource: "@TransferReservationBundle/Resources/config/routing/creneaumodelegen.yml"
    prefix:   /creneaumodelegen
transfer_reservation_creneauRdvGen:
    resource: "@TransferReservationBundle/Resources/config/routing/creneaurdvgen.yml"
    prefix:   /creneaurdvgen
transfer_reservation_typeposte:
    resource: "@TransferReservationBundle/Resources/config/routing/typeposte.yml"
    prefix:   /typeposte
transfer_reservation_rdv:
    resource: "@TransferReservationBundle/Resources/config/routing/rdv.yml"
    prefix: /rdv
transfer_reservation_poste:
    resource: "@TransferReservationBundle/Resources/config/routing/poste.yml"
    prefix: /poste
transfer_reservation_planningprovisoire:
    resource: "@TransferReservationBundle/Resources/config/routing/planningprovisoire.yml"
    prefix: /planningprovisoire
transfer_reservation_planningconfirme:
    resource: "@TransferReservationBundle/Resources/config/routing/planningconfirme.yml"
    prefix: /planningconfirme
transfer_reservation_creneauPref:
    resource: "@TransferReservationBundle/Resources/config/routing/creneaupref.yml"
    prefix: /creneaupref