services:
    transfer_reservation.repository.param_reservation:
        class: Transfer\ReservationBundle\Entity\ParamReservationRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: ['TransferReservationBundle:ParamReservation']
    transfer_reservation.parametres:
        class: Transfer\ReservationBundle\Services\AccesParametres
        arguments: ["@transfer_reservation.repository.param_reservation","@doctrine.orm.entity_manager"]
    transfer_reservation.reservation:
        class: Transfer\ReservationBundle\Services\MoteurReservation
        arguments: ["@doctrine.orm.entity_manager","@transfer_reservation.parametres","@transfer_profil.acces"]
    transfer_reservation.generateur.creneau_modele:
        class: Transfer\ReservationBundle\Generateurs\CreneauModeleGen
        arguments: ["@transfer_reservation.reservation","@transfer_reservation.parametres"]
    transfer_reservation.generateur.creneau_pref:
        class: Transfer\ReservationBundle\Generateurs\CreneauPrefGen
        arguments: ["@transfer_reservation.reservation"]
    transfer_reservation.vidange_listener:
        class: Transfer\ReservationBundle\Event\VidangeListener
        arguments: ["@transfer_reservation.parametres","@transfer_reservation.reservation","@doctrine.orm.entity_manager"]
        tags:
          - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
