Explotic\PlanningBundle\Entity\Calendrier:
    type: entity
    table: null
    repositoryClass: Explotic\PlanningBundle\Entity\CalendrierRepository
    oneToMany:
      dates:
        targetEntity: Explotic\AgendaBundle\Entity\Rdv
        mappedBy: calendrier
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }

