Explotic\PlanningBundle\Entity\Calendrier:
    type: entity
    table: calendrier
    repositoryClass: Explotic\PlanningBundle\Entity\CalendrierRepository
    oneToMany:
      dates:
        targetEntity: Explotic\AgendaBundle\Entity\Rdv
        mappedBy: calendrier
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nom:
          type: string
          length: 255          
    lifecycleCallbacks: {  }

