Explotic\PlanningBundle\Entity\Session:
    type: entity
    table: session
    repositoryClass: Explotic\PlanningBundle\Entity\SessionRepository
    oneToOne:
      calendrier:
        targetEntity: Calendrier
        cascade: ['persist']
    manyToOne:
      salle:
        targetEntity: Explotic\TiersBundle\Entity\Salle
        nullable: true
      poste:
        targetEntity: Explotic\TiersBundle\Entity\Poste
        nullable: true
      interventionSalle:
        targetEntity: Explotic\FormationBundle\Entity\InterventionSalle
        nullable: true
      interventionEntreprise:
        targetEntity: Explotic\FormationBundle\Entity\InterventionEntreprise
        nullable: true
    manyToMany:
      stagiaires:
        targetEntity: Explotic\TiersBundle\Entity\Stagiaire
        mappedBy: sessions
      formateurs:
        targetEntity: Explotic\TiersBundle\Entity\Formateur
        mappedBy: sessions        
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        numero:
          type: string
          length: 255
    lifecycleCallbacks: {  }
