Explotic\PlanningBundle\Entity\Session:
    type: entity
    table: null
    repositoryClass: Explotic\PlanningBundle\Entity\SessionRepository
    oneToOne:
      calendrier:
        targetEntity: Calendrier
    manyToOne:
      salle:
        targetEntity: Explotic\TiersBundle\Entity\Salle
        nullable: true
      poste:
        targetEntity: Explotic\TiersBundle\Entity\Poste
        nullable: true
      intervention:
        targetEntity: Explotic\FormationBundle\Entity\Intervention
    manyToMany:
      stagiaires:
        targetEntity: Explotic\TiersBundle\Entity\Stagiaire
        mappedBy: sessions
      formateurs:
        targetEntity: Explotic\TiersBundle\Entity\Formateur
        mappedBy: sessions        
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        numero:
          type: string
          length: 255
    lifecycleCallbacks: {  }
