Explotic\PlanningBundle\Entity\Session:
    type: entity
    table: session
    repositoryClass: Explotic\PlanningBundle\Entity\SessionRepository
    oneToMany:
      sessionHasInterventionSalles:
        targetEntity: Explotic\PlanningBundle\Entity\SessionHasInterventionSalle
        mappedBy: session
      sessionHasInterventionEntreprises:
        targetEntity: Explotic\PlanningBundle\Entity\SessionHasInterventionEntreprise
        mappedBy: session
    manyToOne:
      module:
        targetEntity: Explotic\FormationBundle\Entity\Module
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        numero:
          type: string
          length: 255
        dateDebut:
          type: date
    lifecycleCallbacks: {  }
