Explotic\TiersBundle\Entity\Bureau:
    type: entity
    table: null
    repositoryClass: Explotic\TiersBundle\Entity\BureauRepository
    oneToOne:
      entreprise:
        targetEntity: Entreprise
        inversedBy: bureau
        cascade: ["persist"]        
    fields:  
        adresseNumero:
            type: integer
        adresseRue:
            type: string
            length: 255         
    lifecycleCallbacks: {  }