Explotic\TiersBundle\Entity\Entreprise:
    type: entity
    table: entreprise
    repositoryClass: Explotic\TiersBundle\Entity\EntrepriseRepository
    oneToOne:
      bureau:
        targetEntity: Explotic\TiersBundle\Entity\Bureau
        joinColumn:
          name: bureau_id
          referencedColumnName: id
        cascade: ["persist"]
    oneToMany:
      stagiaires:
        targetEntity: Stagiaire
        mappedBy: entreprise
        nullable: true
      machines:
        targetEntity: Machine
        mappedBy: entreprise
        nullable: true
      employesrecruteurs:
        targetEntity: Explotic\TiersBundle\Entity\Recruteur
        mappedBy: employeur
        nullable: true
    manyToMany:
      recruteurs:
        targetEntity: Recruteur
        mappedBy: entreprises
        nullable: true
    fields:        
        raisonSociale:
            type: string
            length: 255            
        siret:
            type: string
            length: 255
            nullable: true
        ape:
            type: string
            length: 255            
            nullable: true
        cnil:
            type: string
            length: 255
            nullable: true       
        versionExplotic:
            type: string
            length : 255 
            nullable : true        
        commentaires:
          type: text
          nullable: true
    lifecycleCallbacks: {  }
