Explotic\TiersBundle\Entity\Entreprise:
    type: entity
    table: null
    repositoryClass: Explotic\TiersBundle\Entity\EntrepriseRepository
    oneToOne:
      bureau:
        targetEntity: Explotic\TiersBundle\Entity\Bureau
        joinColumn:
          name: bureau_id
          referencedColumnName: id
        cascade: ["persist"]
      compte:
        targetEntity: Explotic\AdminBundle\Entity\User
        mappedBy: entreprise
        nullable: true
    oneToMany:
      stagiaires:
        targetEntity: stagiaire
        mappedBy: entreprise
      machines:
        targetEntity: Machine
        mappedBy: entreprise
      employesrecruteurs:
        targetEntity: Explotic\TiersBundle\Entity\Recruteur
        mappedBy: employeur
    manyToMany:
      recruteurs:
        targetEntity: Recruteur
        mappedBy: entreprises
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        raisonSociale:
            type: string
            length: 255            
        siret:
            type: string
            length: 255
            nullable: true
        ape:
            type: string
            length: 255            
            nullable: true
        cnil:
            type: string
            length: 255
            nullable: true
        telephone:
            type: string
            length: 255
            nullable: true
        versionExplotic:
            type: string
            length : 255 
            nullable : true
        commentaires:
          type: text
          nullable: true
    lifecycleCallbacks: {  }
