Explotic\TiersBundle\Entity\Entreprise:
    type: entity
    table: entreprise
    repositoryClass: Explotic\TiersBundle\Entity\EntrepriseRepository
    oneToOne:
      gerant:
        targetEntity: Explotic\TiersBundle\Entity\Gerant
        inversedBy: entreprise
        cascade: ["persist"]        
        orphanRemoval: true
      bureau:
        targetEntity: Explotic\TiersBundle\Entity\Bureau
        mappedBy: entreprise
        joinColumn:
          name: bureau_id
          referencedColumnName: id
        cascade: ["all"]        
        orphanRemoval: true
    oneToMany:
      stagiaires:
        targetEntity: Stagiaire
        mappedBy: entreprise
        nullable: true
        cascade: ["persist"]
      machines:
        targetEntity: Machine
        mappedBy: entreprise
        nullable: true
        cascade: ["persist"]        
        orphanRemoval: true
      employesrecruteurs:
        targetEntity: Explotic\TiersBundle\Entity\Recruteur
        mappedBy: employeur
        nullable: true
        cascade: ["persist"]
    manyToMany:
      recruteurs:
        targetEntity: Recruteur
        mappedBy: entreprises
        nullable: true
        cascade: ["persist"]
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        raisonSociale:
            type: string
            length: 255  
        donneurOrdre:
            type: string
            length: 255
        telephone:
            type: string
            length: 255
            nullable: true
        email:
            type: string
            length: 255
            nullable: true            
        siret:
            type: string
            length: 255
            nullable: true
        ape:
            type: string
            length: 255            
            nullable: true
        cnil:
            type: string
            length: 255
            nullable: true       
        versionExplotic:
            type: string
            length : 255 
            nullable : true        
        commentaires:
          type: text
          nullable: true          
    lifecycleCallbacks: {  }
