Explotic\TiersBundle\Entity\Formateur:
    type: entity
    table: formateur
    repositoryClass: Explotic\TiersBundle\Entity\FormateurRepository
    oneToOne:
      calendrier:
        targetEntity: Explotic\PlanningBundle\Entity\Calendrier
        cascade: ['persist']
    manyToOne:
      organisme:
        targetEntity: Organisme
        inversedBy: formateur
    oneToMany:
      interventionHasFormateurs:
        targetEntity: Explotic\PlanningBundle\Entity\InterventionHasFormateur
        mappedBy: formateurs        
    lifecycleCallbacks: {  }
