Explotic\TiersBundle\Entity\Formateur:
    type: entity
    table: formateur
    repositoryClass: Explotic\TiersBundle\Entity\FormateurRepository
    oneToOne:
      calendrier:
        targetEntity: Explotic\PlanningBundle\Entity\Calendrier     
    manyToOne:
      Organisme:
        targetEntity: Organisme
    manyToMany:
      sessions:
        targetEntity: Explotic\PlanningBundle\Entity\Session
        inversedBy: formateurs
        joinTable:
          name: formateurs_sessions
          joinColumns:
            formateur_id:
              referencedColumnName: id
          inverseJoinColumns:
            session_id:
              referencedColumnName: id     
    lifecycleCallbacks: {  }
