Explotic\TiersBundle\Entity\Geometry:
    type: entity
    table: geometry
    repositoryClass: Explotic\TiersBundle\Entity\GeometryRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        lat:
            type: float
        lon:
            type: float
    lifecycleCallbacks: {  }
