Explotic\TiersBundle\Entity\Machine:
    type: entity
    table: machine
    repositoryClass: Explotic\TiersBundle\Entity\MachineRepository
    manyToOne:
      entreprise:
        targetEntity: Explotic\TiersBundle\Entity\Entreprise
        inversedBy: machines
        cascade: ["persist"]
    oneToMany:
      stagiaires:
        targetEntity: Explotic\TiersBundle\Entity\Stagiaire
        mappedBy: machine
        nullable: true
        cascade: ["persist"]   
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        numeroEntreprise:
            type: integer
            nullable: true
        reference:
            type: string
            length: 255 
            nullable: true
        modele:
            type: string
            length: 255   
            nullable: true
        marque:
            type: string
            length: 255   
            nullable: true
        logiciel:
            type: string
            length: ENUM("TM300","H09","OPTI4G","OPTI5G","Autre")
        transfertData:
            type: boolean
        forfait: 
            type: string
            length: 255   
            nullable: true
        commentaire:
            type: text    
            nullable: true
        email:
            type: string
            length: 255   
            nullable: true
    lifecycleCallbacks: {  }
