Explotic\TiersBundle\Entity\Poste:
    type: entity
    table: null
    repositoryClass: Explotic\TiersBundle\Entity\PosteRepository
    manyToOne:
      stagiaire:
        targetEntity: Stagiaire
        inversedBy: postes
        cascade: ["persist"]
    fields:
        nomChantier:
            type: string
            length: 255
    lifecycleCallbacks: {  }