Explotic\TiersBundle\Entity\Recruteur:
  type: entity
  table: recruteur
  repositoryClass: Explotic\TiersBundle\Entity\RecruteurRepository
  manyToOne:
    employeur:
      targetEntity: Explotic\TiersBundle\Entity\Entreprise
      inversedBy: employesrecruteurs
      cascade: ["persist"]
  oneToMany:
    stagiaires:
      targetEntity: Explotic\TiersBundle\Entity\Stagiaire
      mappedBy: recruteur
      nullable: true     
      cascade: ["persist"]
  manyToMany:
    entreprises:
      targetEntity: Entreprise
      inversedBy: recruteurs      
      cascade: ["persist"]
      joinTable:
        name: recruteurs_entreprises
        joinColumns:
          recruteur_id: 
            referencedColumnName: id
        inverseJoinColumns :
          entreprise_id:
            referencedColumnName: id    
  lifecycleCallbacks: {  }
