Explotic\TiersBundle\Entity\Stagiaire:
    type: entity
    table: stagiaire
    repositoryClass: Explotic\TiersBundle\Entity\StagiaireRepository
    oneToOne:
      calendrier:
        targetEntity: Explotic\PlanningBundle\Entity\Calendrier
        cascade: ["persist"]
      creditTemps:
        targetEntity: Explotic\PlanningBundle\Entity\CreditTemps
        cascade: ["persist"]
    oneToMany:      
      postes:
        targetEntity: Explotic\TiersBundle\Entity\Poste
        mappedBy: stagiaire 
        cascade: ["persist"]
        orphanRemoval: true
      programmes:
        targetEntity: Explotic\FormationBundle\Entity\Programme
        mappedBy: stagiaire 
        cascade: ["persist"]
        orphanRemoval: true
    manyToOne:
      entreprise:
        targetEntity: Entreprise
        inversedBy: stagiaires 
        nullable: true
        cascade: ["persist"]
      machine:
        targetEntity: Machine
        inversedBy: stagiaires
        nullable: true
        cascade: ["persist"]
      recruteur:
        targetEntity: Recruteur
        inversedBy: stagiaires 
        nullable: true
    manyToMany:
      sessions:
        targetEntity: Explotic\PlanningBundle\Entity\Session
        inversedBy: stagiaires
        nullable: true
        cascade: ["persist"]
        joinTable:
          name: stagiaires_sessions
          joinColumns:
            stagiaire_id:
              referencedColumnName: id
          inverseJoinColumns:
            session_id:
              referencedColumnName: id             
    fields:        
        marchePiedInfo:
            type: boolean        
        gerant:
          type: boolean
          nullable: true
        forfaitTelephone:
          type: string
          length: 255  
          nullable: true
        niveauInfo:
          type: string
          columnDefinition: ENUM("faible","moyen","bon","NC")
        typeEmploi:
          type: string
          length: 255
          nullable: true
        opca:
          type: string
          columnDefinition: ENUM("VIVEA","FAFSEA","OPCA3+")
        commentaire:
          type: text
          nullable: true
    lifecycleCallbacks: {  }
