Explotic\TiersBundle\Entity\Stagiaire:
    type: entity
    table: null
    repositoryClass: Explotic\TiersBundle\Entity\StagiaireRepository
    oneToOne:
      calendrier:
        targetEntity: Explotic\PlanningBundle\Entity\Calendrier
        cascade: ["persist"]
      creditTemps:
        targetEntity: Explotic\PlanningBundle\Entity\CreditTemps
        cascade: ["persist"]
      compte:
        targetEntity: Explotic\AdminBundle\Entity\User
        mappedBy: stagiaire
        nullable: true
    oneToMany:
      postes:
        targetEntity: Explotic\TiersBundle\Entity\Poste
        mappedBy: stagiaire 
        cascade: ["persist"]
      programmes:
        targetEntity: Explotic\FormationBundle\Entity\Programme
        mappedBy: stagiaire 
        cascade: ["persist"]
    manyToOne:
      entreprise:
        targetEntity: Entreprise
        inversedBy: stagiaires 
        nullable: true
      machine:
        targetEntity: Machine
        inversedBy: stagiaires
        nullable: true
        nullable: true
      recruteur:
        targetEntity: Recruteur
        inversedBy: stagiaires 
        nullable: true
    manyToMany:
      sessions:
        targetEntity: Explotic\PlanningBundle\Entity\Session
        inversedBy: stagiaires
        nullable: true
        joinTable:
          name: stagiaires_sessions
          joinColumns:
            stagiaire_id:
              referencedColumnName: id
          inverseJoinColumns:
            session_id:
              referencedColumnName: id             
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nom:
            type: string
            length: 255
        prenom:
            type: string
            length: 255
        dateNaissance:
            type: datetime
            nullable: true
        marchePiedInfo:
            type: boolean
        telephone:
            type: string
            length: 255
            nullable: true
        gerant:
          type: boolean
          nullable: true
        forfaitTelephone:
          type: string
          length: 255  
          nullable: true
        niveauInfo:
          type: string
          columnDefinition: ENUM("faible","moyen","bon","NC")
        typeEmploi:
          type: string
          length: 255
          nullable: true
        opca:
          type: string
          columnDefinition: ENUM("VIVEA","FAFSEA","OPCA3+")
        commentaire:
          type: text
          nullable: true
    lifecycleCallbacks: {  }
