<?php

namespace Transfer\ReservationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CreneauPrefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreneauPrefRepository extends EntityRepository
{
    
    public function findActifsByTransporteur($idTransporteur){
        $query = $this->getEntityManager()->createQuery(
                "SELECT cp
                FROM TransferReservationBundle:CreneauPref cp
                JOIN cp.transporteur t
                JOIN cp.statut st
                WHERE st.nom = 'Actif'
                AND t.id = :idTrsp
                ");
        $query->setParameter('idTrsp', $idTransporteur);
        return $query->getResult();
    }
    public function findActifsByPoste(){
        $query = $this->getEntityManager()->createQuery(
                "SELECT cp
                FROM TransferReservationBundle:CreneauPref cp
                JOIN cp.statut st
                WHERE st.nom = 'Actif'
                ");
        return $query->getResult();
    }
    
    public function findOrdered(){
        $query = $this->getEntityManager()->createQuery("
            SELECT cp
            FROM TransferReservationBundle:CreneauPref cp
            JOIN cp.transporteur t
            JOIN cp.statut st
            JOIN cp.etatReservation er
            JOIN cp.creneauModele cm
            WHERE st.nom='Actif'
            ORDER BY t.priorite DESC, cm.jour ASC, cm.heure ASC, cm.minute ASC
            ");
        return $query->getResult();
    }
}
