<?php

namespace Transfer\ReservationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CreneauRdvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreneauRdvRepository extends EntityRepository
{
    public function findByRecherche($rdvRecherche){

        $query = $this->getEntityManager()->createQuery(
        "SELECT cr
        FROM TransferReservationBundle:CreneauRdv cr
        JOIN cr.typePoste t
        WHERE  cr.disponibilite <> 0
        AND t.id = :posteId
        AND cr.dateHeureDebut BETWEEN :min AND :max
        ");
        // Construction de l'interval de temps de recherche
        $interval = new \DateInterval('PT35M'); //Période de Temps de 30 min
        $min = clone $rdvRecherche->getDateHeureDebut();
        $min->sub($interval);
        $max = clone $rdvRecherche->getDateHeureDebut(); 
        $max->add($interval);
        //
        $query->setParameters(array(
            'posteId'=> $rdvRecherche->getTypePoste()->getId(),
            'min'=> $min,
            'max'=> $max
                ));
        
        return $query->getResult();
    }
    
    public function findByAnnee_Semaine_Poste($annee, $semaine,$poste){
        $query = $this->getEntityManager()->createQuery(
                'SELECT cr
                FROM TransferReservationBundle:CreneauRdv cr
                JOIN cr.typePoste p
                WHERE cr.semaine = :semaine                
                AND cr.annee = :annee
                AND p.nom = :nomPoste
                '
                );
        $query->setParameters(array(
            'semaine'=> $semaine,
            'annee'=> $annee,
            'nomPoste'=> $poste->getNom(),
                ));
        return $query->getResult();
    }
}
