<?php

namespace Transfer\ReservationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CreneauPrefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreneauPrefRepository extends EntityRepository
{
    
    public function findActifsByTransporteur($idTransporteur){
        $query = $this->getEntityManager()->createQuery(
                "SELECT cp
                FROM TransferReservationBundle::CreneauPref cp
                JOIN cp.TransferProfilBundle::Transporteur t
                JOIN cp.TransferReservationBundle::StatutCreneau st
                WHERE st.id = 'Actif'
                AND t.id = :idTrsp
                ORDER BY cp.jour, cp.heure, cp.minute
                ");
        $query->setParameter('idTrsp', $idTransporteur);
        return $query->getResult();
    }
}
