<?php

namespace Transfer\ReservationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CreneauModeleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreneauModeleRepository extends EntityRepository
{
    public function findDisponibles(){
        $qb = $this->getEntityManager()->createQueryBuilder();
        
        $subqb = $this->getEntityManager()->createQueryBuilder();
        
        $subqb  ->select('cm0')
                ->from('TransferReservationBundle:CreneauModele','cm0 ')
                ->leftjoin('cm0.creneauxPrefs', 'cp')
                ->groupBy('cm0')
                ->having('count(cp)>0')
                ;

        $qb ->select('cm')
            ->from('TransferReservationBundle:CreneauModele','cm ')
            ->where($qb->expr()->notin('cm', $subqb->getDQL()))
            ;      
        
        return $qb;                
    }

       
    public function findByNomStatut($nomStatut){
        return $this->getEntityManager()
                ->createQuery('
                    SELECT cm
                    FROM TransferReservationBundle:CreneauModele cm
                    JOIN cm.statut st
                    WHERE st.nom = :nomStatut
                    ORDER BY cm.jour, cm.heureDebut
                    ')
                ->setParameter(':nomStatut',$nomStatut)
                ->getResult();
    }
        public function findActifsByPoste($poste){
        return $this->getEntityManager()
                ->createQuery('
                    SELECT cm
                    FROM TransferReservationBundle:CreneauModele cm
                    JOIN cm.statut st
                    JOIN cm.typePoste p
                    WHERE st.nom = :statut
                    AND p.id = :idPoste
                    ORDER BY cm.jour, cm.heureDebut
                    ')
                ->setParameter(':idPoste',$poste->getId())
                ->setParameter(':statut','Actif')
                ->getResult();
    }
    public function findSemaineMinutesMin($poste){
        
        $query = $this->getEntityManager()->createQuery();
        
        $query->setDQL('
                        SELECT min(c.heureDebut)
                        FROM TransferReservationBundle:CreneauModele c
                        JOIN c.typePoste p
                        WHERE p.id = :idPoste
                ')
                ->setParameter('idPoste', $poste->getId());   
        
        return $query->getSingleScalarResult();        
    }
}
