<?php

namespace Transfer\ReservationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RdvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RdvRepository extends EntityRepository
{
    
    public function findByTransporteur($transporteur){
        
        $query = $this->getEntityManager()->createQuery();
        
        $query->setDQL('
                        SELECT r
                        FROM TransferReservationBundle:Rdv r
                        JOIN r.evenements e
                        JOIN e.transporteur t
                        WHERE t.id = :id
                ')
                ->setParameter('id', $transporteur->getId());
        
        return $query->getResult();        
    }
    
    public function findByTransporteur_Annee_Semaine_Poste($transporteur, $annee, $semaine,$poste){
        
        $query = $this->getEntityManager()->createQuery();
        
        $query->setDQL('
                        SELECT r
                        FROM TransferReservationBundle:Rdv r
                        JOIN r.evenements e
                        JOIN e.transporteur t
                        JOIN r.creneauRdv c
                        JOIN c.typePoste p
                        WHERE t.id = :id
                        AND c.semaine = :semaine
                        AND c.annee = :annee
                        AND p.nom = :nomPoste
                ')
                ->setParameter('id', $transporteur->getId())
                ->setParameter('nomPoste', $poste->getNom())
                ->setParameter('semaine', $semaine)
                ->setParameter('annee', $annee);        
        
        return $query->getResult();        
    }
    public function findSemaineMinutesMin($annee, $semaine,$poste){
        
        $query = $this->getEntityManager()->createQuery();
        
        $query->setDQL('
                        SELECT min(c.heureDebut)
                        FROM TransferReservationBundle:CreneauRdv c
                        JOIN c.typePoste p
                        WHERE c.semaine = :semaine
                        AND c.annee = :annee
                        AND p.id = :idPoste
                ')
                ->setParameter('idPoste', $poste->getId())
                ->setParameter('semaine', $semaine)
                ->setParameter('annee', $annee);        
        
        return $query->getSingleScalarResult();        
    }
    
    public function findByStatutRdvForTrsp($statut,$transporteur){
                
        $query = $this->getEntityManager()->createQuery();
        
        $query->setDQL('
                        SELECT r
                        FROM TransferReservationBundle:Rdv r
                        JOIN r.evenements e
                        JOIN e.transporteur t
                        WHERE t.id = :id
                        AND r.statutRdv = :statut
                ')
                ->setParameter('id', $transporteur->getId())
                ->setParameter('statut', $statut);
        
        return $query->getResult();        
    }   
    
    public function findByStatutRdv($transporteur, $annee,$semaine,$statut){
        $query = $this->getEntityManager()->createQuery();
        
        $query->setDQL('
                        SELECT r
                        FROM TransferReservationBundle:Rdv r
                        JOIN r.evenements e
                        JOIN e.transporteur t
                        JOIN r.creneauRdv c
                        WHERE t.id = :id
                        AND c.semaine = :semaine
                        AND c.annee = :annee
                        AND r.statutRdv = :statut
                        ORDER BY c.dateHeureDebut ASC
                ')
                ->setParameter('id', $transporteur->getId())
                ->setParameter('semaine', $semaine)
                ->setParameter('annee', $annee)
                ->setParameter('statut',$statut);
        
        return $query->getResult();        
    }
      
            
}
