creneauprefgen_selecttypecamion:
    pattern:  /selecttypecamion
    defaults: { _controller: "TransferReservationBundle:CreneauPrefGen:selectTypeCamion" }
    
creneauprefgen_generate_ajax:
    pattern:  /generate_ajax
    defaults: { _controller: "TransferReservationBundle:CreneauPrefGen:generateAjax" }
#    requirements: { _method: post }
    
creneauprefgen_generate:
    pattern:  /generate/{typeCamionId}
    defaults: { _controller: "TransferReservationBundle:CreneauPrefGen:generate" }

creneauprefgen_create:
    pattern:  /create
    defaults: { _controller: "TransferReservationBundle:CreneauPrefGen:create" }
    requirements: { _method: post }
    

