planningconfirme:
    pattern:  /
    defaults: { _controller: "TransferReservationBundle:PlanningConfirme:index" }

planningconfirme_show:
    pattern:  /{id}/show
    defaults: { _controller: "TransferReservationBundle:PlanningConfirme:show" }

planningconfirme_new:
    pattern:  /new
    defaults: { _controller: "TransferReservationBundle:PlanningConfirme:new" }

planningconfirme_create:
    pattern:  /create
    defaults: { _controller: "TransferReservationBundle:PlanningConfirme:create" }
    requirements: { _method: post }

planningconfirme_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "TransferReservationBundle:PlanningConfirme:edit" }

planningconfirme_update:
    pattern:  /{id}/update
    defaults: { _controller: "TransferReservationBundle:PlanningConfirme:update" }
    requirements: { _method: post }

planningconfirme_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "TransferReservationBundle:PlanningConfirme:delete" }
    requirements: { _method: post }
