rdv:
    pattern:  /
    defaults: { _controller: "TransferReservationBundle:Rdv:index" }

rdv_show:
    pattern:  /{id}/show
    defaults: { _controller: "TransferReservationBundle:Rdv:show" }
    
rdv_transporteur:
    pattern: /transporteur/{annee}/{semaine}
    defaults: {_controller: "TransferReservationBundle:Rdv:showTransporteur"}
    
rdv_new:
    pattern:  /new
    defaults: { _controller: "TransferReservationBundle:Rdv:new" }

rdv_create:
    pattern:  /create
    defaults: { _controller: "TransferReservationBundle:Rdv:create" }
    requirements: { _method: post }

rdv_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "TransferReservationBundle:Rdv:edit" }

rdv_update:
    pattern:  /{id}/update
    defaults: { _controller: "TransferReservationBundle:Rdv:update" }
    requirements: { _method: post }

rdv_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "TransferReservationBundle:Rdv:delete" }
    requirements: { _method: post }
    
rdv_reservation:
    pattern: /reservation
    defaults: {_controller: "TransferReservationBundle:Rdv:reservationRecherche" }

rdv_reservation_proche:
    pattern: /reservation/{idRdv}/{mode}
    defaults: {_controller: "TransferReservationBundle:Rdv:reservationProche" }
    requirements: { _method: post}

rdv_confirmation:
    pattern: /confirmation/{id}
    defaults: {_controller: "TransferReservationBundle:Rdv:confirmation" }
    requirements: { _method: post }
    
