parameters:
#    explotic_formation.example.class: Explotic\FormationBundle\Example

services:
#    explotic_tiers.admin.programme:
#        class: Explotic\ProgrammeAdmin\Admin\ProgrammeAdmin
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: Gestion des programmes, label: Liste des programmes}
#        arguments: [null, Explotic\TiersBundle\Entity\Programme, null]
