<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\MediaBundle\Entity;

use Sonata\MediaBundle\Entity\BaseGallery as BaseGallery;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Gallery extends BaseGallery
{
    /**
     * @var integer $id
     */
    protected $id;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }
    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $children;

    /**
     * @var \Application\Sonata\MediaBundle\Entity\Gallery
     */
    private $parent;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->children = new \Doctrine\Common\Collections\ArrayCollection();
        
    }
    
    /**
     * Add children
     *
     * @param \Application\Sonata\MediaBundle\Entity\Gallery $children
     * @return Gallery
     */
    public function addChildren(\Application\Sonata\MediaBundle\Entity\Gallery $children)
    {
        $this->children[] = $children;
    
        return $this;
    }

    /**
     * Remove children
     *
     * @param \Application\Sonata\MediaBundle\Entity\Gallery $children
     */
    public function removeChildren(\Application\Sonata\MediaBundle\Entity\Gallery $children)
    {
        $this->children->removeElement($children);
    }

    /**
     * Get children
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getChildren()
    {
        return $this->children;
    }

    /**
     * Set parent
     *
     * @param \Application\Sonata\MediaBundle\Entity\Gallery $parent
     * @return Gallery
     */
    public function setParent(\Application\Sonata\MediaBundle\Entity\Gallery $parent = null)
    {
        $this->parent = $parent;
    
        return $this;
    }

    /**
     * Get parent
     *
     * @return \Application\Sonata\MediaBundle\Entity\Gallery 
     */
    public function getParent()
    {
        return $this->parent;
    }

   

    /**
     * @var string
     */
    private $authorization;

    

    /**
     * Set authorization
     *
     * @param string $authorization
     * @return Gallery
     */
    public function setAuthorization($authorization)
    {
        $this->authorization = $authorization;
    
        return $this;
    }

    /**
     * Get authorization
     *
     * @return string 
     */
    public function getAuthorization()
    {
        return $this->authorization;
    }

    
}