Transfer\ReservationBundle\Entity\CreneauPref:
  type: entity
  table: null
  repositoryClass: Transfer\ReservationBundle\Entity\CreneauPrefRepository
  manyToOne:
    creneauModele:
      targetEntity: CreneauModele
      inversedBy: creneauxPrefs
    transporteur:
      targetEntity: Transfer\ProfilBundle\Entity\Transporteur
      inversedBy: creneauPrefs
    etatReservation:
      targetEntity: EtatReservation      
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    disponibilite:
      type: integer
  lifecycleCallbacks: {  }
