Transfer\ReservationBundle\Entity\CreneauRdv:
    type: entity
    table: null
    repositoryClass: Transfer\ReservationBundle\Entity\CreneauRdvRepository
    oneToMany:
      rdvs:
        targetEntity: Rdv
        mappedBy: creneauRdv    
    fields:
        semaine:
            type: integer
        annee:
            type: integer
    lifecycleCallbacks: {  }
