Transfer\ReservationBundle\Entity\CreneauPref:
  type: entity
  table: null
  repositoryClass: Transfer\ReservationBundle\Entity\CreneauPrefRepository
  manyToOne:
    creneauModelePref:
      targetEntity: CreneauModele
      inversedBy: creneauPrefModeles
    transporteurPref:
      targetEntity: Transfer\ProfilBundle\Entity\Transporteur
      inversedBy: creneauPrefs
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    Disponibilite:
      type: integer
  lifecycleCallbacks: {  }
