Transfer\ReservationBundle\Entity\Creneau:
    type: entity
    table: null
    repositoryClass: Transfer\ReservationBundle\Entity\CreneauRepository
    manyToOne:
      typePoste:
        targetEntity: TypePoste 
      statut:
          targetEntity: StatutCreneau
    oneToMany:
      disponibilites:
        targetEntity: Disponibilite
        mappedBy: creneau
        cascade: ["all"]
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        jour:
            type: integer
        heure:
            type: integer
        minute:
            type: integer
        duree:
            type: integer
        heureDebut:
            type: time
        heureFin:
            type: time
        disponibiliteTotale:
            type: integer
        dateCreation:
            type: date
        dateArchivage:
            type: date
            nullable: true
        dateModification:
            type: date            
    inheritanceType: JOINED
    discriminatorColumn:
      name: typeCreneau
      type: string
      length: 255
    discriminatorMap:
      creneauRdv : CreneauRdv
      creneauModele: CreneauModele
    lifecycleCallbacks: {  }
