Transfer\ReservationBundle\Entity\CreneauRdv:
    type: entity
    table: null
    repositoryClass: Transfer\ReservationBundle\Entity\CreneauRdvRepository
    oneToMany:
      rdvs:
        targetEntity: Rdv
        mappedBy: creneauRdv    
    fields:
      dateHeureDebut:
        type: datetime
      dateHeureFin:
        type: datetime
      semaine:
          type: integer
      annee:
          type: integer
    lifecycleCallbacks: {  }
