Transfer\ReservationBundle\Entity\CreneauModele:
    type: entity
    table: null
    repositoryClass: Transfer\ReservationBundle\Entity\CreneauModeleRepository          
    lifecycleCallbacks: {  }
