Transfer\ReservationBundle\Entity\CreneauModele:
    type: entity
    table: creneaumodele
    oneToMany:
      creneauxPrefs:
        targetEntity: CreneauPref
        mappedBy: creneauModele                  
    repositoryClass: Transfer\ReservationBundle\Entity\CreneauModeleRepository               
    lifecycleCallbacks: {  }
