Transfer\ReservationBundle\Entity\CreneauPref:
  type: entity
  table: creneaupref
  repositoryClass: Transfer\ReservationBundle\Entity\CreneauPrefRepository
  manyToOne:
    creneauModele:
      targetEntity: CreneauModele
      inversedBy: creneauxPrefs
    transporteur:
      targetEntity: Transfer\ProfilBundle\Entity\Transporteur
      inversedBy: creneauPrefs
    etatReservation:
      targetEntity: EtatReservation     
    statut:
      targetEntity: StatutCreneau
    typeCamion:
      targetEntity: TypeCamion      
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  lifecycleCallbacks: {  }
