Transfer\ReservationBundle\Entity\Disponibilite:
    type: entity
    table: disponibilite
    repositoryClass: Transfer\ReservationBundle\Entity\DisponibiliteRepository
    manyToOne:
      typeCamion:
        targetEntity: TypeCamion
      creneau:
        targetEntity: Creneau
        inversedBy: disponibilites
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        valeur:
            type: integer
    lifecycleCallbacks: {  }
