Transfer\ReservationBundle\Entity\ParamReservation:
    type: entity
    table: paramreservation
    repositoryClass: Transfer\ReservationBundle\Entity\ParamReservationRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        parametres:
            type: array
        parametresReserves:
            type: array        
    lifecycleCallbacks: {  }
