Transfer\ReservationBundle\Entity\PlanningProvisoire:
    type: entity
    table: null
    repositoryClass: Transfer\ReservationBundle\Entity\PlanningProvisoireRepository
    oneToMany:
      rdvs:
        targetEntity: Rdv
        mappedBy: planningProvisoire 
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        limite:
            type: integer
    lifecycleCallbacks: {  }
