Transfer\ReservationBundle\Entity\Rdv:
    type: entity
    table: rdv
    repositoryClass: Transfer\ReservationBundle\Entity\RdvRepository
    oneToMany:
      evenements:
        targetEntity: Evenement
        mappedBy: rdv
        cascade: ["all"]          
    manyToOne:
      creneauRdv:
        targetEntity: CreneauRdv
        inversedBy: rdvs     
      typeCamion:
        targetEntity: TypeCamion        
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        statutRdv:
            type: string
            columnDefinition: ENUM('provisoire','confirme','annule')            
    lifecycleCallbacks: {  }
