Transfer\ReservationBundle\Entity\Transporteur:
    type: entity
    table: null
    repositoryClass: Transfer\ReservationBundle\Entity\TransporteurRepository
    oneToMany:
      rdvs:
        targetEntity: Rdv
        mappedBy: transporteurPlanif
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nom:
            type: string
            length: 255
        priorite:
            type: integer
        quota:
            type: integer
    lifecycleCallbacks: {  }
