<?php

namespace Transfer\ProfilBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AgentDabRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgentDabRepository extends EntityRepository
{
}
