<?php

namespace Transfer\ProfilBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TransporteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransporteurRepository extends EntityRepository
{
    
    public function testAutorisation($annee,$semaine, $id){
        $query= $this->getEntityManager()->createQuery("
                    SELECT count(r)-t.quota
                    FROM TransferProfilBundle:Transporteur t
                    JOIN t.evenements e
                    JOIN e.rdv r
                    JOIN r.creneauRdv cr
                    WHERE cr.semaine = :semaine
                    AND cr.annee = :annee
                    AND r.statutRdv = 'confirme'
                    AND t.id= :id
                    GROUP BY t.id
                    ")
                    ->setParameters(array(
                        'id'=>$id,
                        'semaine'=>$semaine,
                        'annee'=>$annee,
                    ));
        return $query->getResult();
                        
    }
}
