<?php

namespace Explotic\TiersBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntrepriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntrepriseRepository extends EntityRepository
{
    public function findByStagiaire($id){
        $query = $this->getEntityManager()
                ->createQuery('
                    SELECT e 
                    FROM ExploticTiersBundle:Stagiaire s JOIN s.entreprise e
                    WHERE s.id=1'
                )->setParameter('id', $id);
        try{
            return $query->getSingleResult();
        }catch (\Doctrine\ORM\NoResultException $e){
            return null;
        }
        
    }
       
}
