<?php

namespace Explotic\TiersBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GeometryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeometryRepository extends EntityRepository
{
}
