<?php

namespace Explotic\TiersBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MachineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MachineRepository extends EntityRepository
{
    public function choiceLimiter($entrepriseId){
        return createQueryBuilder('m')
                    ->from('ExploticTiersBundle:Machine','m')                                      
                    ->leftJoin('m.entreprise','ent')
                    ->andWhere('ent.id = :id')
                    ->setParameter('id',$entrepriseId)
                    ;
    }
    
}
