<?php

namespace Explotic\TiersBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RecruteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecruteurRepository extends EntityRepository
{

}
