<?php

namespace Explotic\TiersBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StagiaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StagiaireRepository extends EntityRepository
{
    public function findAuthorized(\Explotic\AdminBundle\Entity\User $user){
        $query = $this->getEntityManager()->createQuery("
            SELECT st
            FROM ExploticTiersBundle:Stagiaire st
            JOIN st.recruteur r
            JOIN st.entreprise ent
            JOIN st.session s
            JOIN s.formateurs f
            WHERE r.id = :userId
            OR ent.id = :userId
            OR f.id = :userId
            ");
        $query->setParameter('userId', $user->getId());
        return $query->getResult();
    }
}
