explotic_agenda:
    resource: "@ExploticAgendaBundle/Resources/config/routing.yml"
    prefix:   /

explotic_main:
    resource: "@ExploticMainBundle/Resources/config/routing.yml"
    prefix:   /

explotic_admin:
    resource: "@ExploticAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

explotic_formation:
    resource: "@ExploticFormationBundle/Resources/config/routing.yml"
    prefix:   /formation

explotic_planning:
    resource: "@ExploticPlanningBundle/Resources/config/routing.yml"
    prefix:   /planning

explotic_tiers:
    resource: "@ExploticTiersBundle/Resources/config/routing.yml"
    prefix:   /tiers

# app/config/routing.yml
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#Sonata routing
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
 
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin   
    
#SonataUserBundle
sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin
    
#SonataMediaBundle
gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery
    
media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media    
    
    
# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
