transfer_main:
    resource: "@TransferMainBundle/Resources/config/routing.yml"
    prefix:   /

transfer_profil:
    resource: "@TransferProfilBundle/Resources/config/routing.yml"
    prefix:   /profil

transfer_reservation:
    resource: "@TransferReservationBundle/Resources/config/routing.yml"
    prefix:   /reservation
transfer_reservation_dab:
    resource: "@TransferReservationBundle/Resources/config/routingDab.yml"
    prefix:   /dab

# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

#fos user bundle routing
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile