jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface : sha512        

    role_hierarchy:
        ROLE_GERANT : ROLE_SUPER_USER
        ROLE_RECRUTEUR : ROLE_SUPER_USER
        ROLE_FORMATEUR : ROLE_SUPER_USER
        ROLE_ADMIN:       [ROLE_STAGIAIRE, ROLE_RECRUTEUR, ROLE_FORMATEUR, ROLE_GERANT]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
            
    firewalls: 
    #!!!!WARNING!!!! :  l'ordre des firewalls détermine l'ordre de lecture par
    #                   le kernel...
      
        #firewall par défaut
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        #Firewall pour les pages de connexion
        login:
          pattern: ^/(login$|register|resetting)
          anonymous: true
          
        #Firewall principal du site
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            remember_me:
              key: %secret%
            logout: true
            anonymous: false
            
    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/admin, roles: ROLE_ADMIN}

        
        #- { path: ^/formation/, roles: ROLE_ADMIN}
        
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
    
    