Transfer\MainBundle\Entity\Group:
    type: entity
    table: fos_group
    repositoryClass: Transfer\MainBundle\Entity\GroupRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO      
    lifecycleCallbacks: {  }
