Transfer\MainBundle\Entity\User:
    type: entity
    table: fos_user
    repositoryClass: Transfer\MainBundle\Entity\UserRepository
    oneToOne:
        profil:
            targetEntity: Transfer\ProfilBundle\Entity\Profil
            mappedBy: user
            nullable: true
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO      
    lifecycleCallbacks: {  }
