Transfer\MainBundle\Entity\User:
    type: entity
    table: fos_user
    repositoryClass: Transfer\MainBundle\Entity\UserRepository
    oneToOne:
        agentDab:
            targetEntity: Transfer\ProfilBundle\Entity\AgentDab
            inversedBy: user
            nullable: true
        agentTrsp:
            targetEntity: Transfer\ProfilBundle\Entity\AgentTrsp
            inversedBy: user
            nullable: true
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO      
    lifecycleCallbacks: {  }
