Transfer\MainBundle\Entity\User:
    type: entity
    table: fos_user
    repositoryClass: Transfer\MainBundle\Entity\UserRepository
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
      name: profil
      type: string
      length: 255
    discriminatorMap:
      agentdab:       Transfer\ProfilBundle\Entity\AgentDab
      agenttrsp:      Transfer\ProfilBundle\Entity\AgentTrsp
      agentreception: Transfer\ProfilBundle\Entity\AgentReception
      user:           Transfer\MainBundle\Entity\User
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO      
    lifecycleCallbacks: {  }
