stagiaire:
    pattern:  /
    defaults: { _controller: "ExploticTiersBundle:Stagiaire:index" }

stagiaire_show:
    pattern:  /{id}/show
    defaults: { _controller: "ExploticTiersBundle:Stagiaire:show" }

stagiaire_new:
    pattern:  /new
    defaults: { _controller: "ExploticTiersBundle:Stagiaire:new" }

stagiaire_create:
    pattern:  /create
    defaults: { _controller: "ExploticTiersBundle:Stagiaire:create" }
    requirements: { _method: post }

stagiaire_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ExploticTiersBundle:Stagiaire:edit" }

stagiaire_update:
    pattern:  /{id}/update
    defaults: { _controller: "ExploticTiersBundle:Stagiaire:update" }
    requirements: { _method: post }

stagiaire_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ExploticTiersBundle:Stagiaire:delete" }
    requirements: { _method: post }

stagiaire_programmation:
    pattern: /{id}/programmation
    defaults: {_controller: "ExploticTiersBundle:Stagiaire:programmation"}
    requirements: { _method: get }

stagiaire_entreprise:
    pattern: /entreprise/{id}
    defaults: {_controller: "ExploticTiersBundle:Stagiaire:voirEntreprise"}
    requirements: { _method: get }

stagiaire_bureau:
    pattern: /bureau/{id}
    defaults: {_controller: "ExploticTiersBundle:Stagiaire:voirBureau"}
    requirements: { _method: get }

stagiaire_postes:
    pattern: /postes/{id}
    defaults: {_controller: "ExploticTiersBundle:Stagiaire:voirPostes"}
    requirements: { _method: get }
  