explotic_planning_credittemps:
    resource: "@ExploticPlanningBundle/Resources/config/routing/credittemps.yml"
    prefix:   /credittemps
explotic_planning_session:
    resource: "@ExploticPlanningBundle/Resources/config/routing/session.yml"
    prefix:   /session
