parameters:
  explotic_planning.agenda_generator.class: Explotic\PlanningBundle\Services\AgendaGenerator

services:
  explotic_planning.agenda_generator:
    class: %explotic_planning.agenda_generator.class%
    arguments:  ["@doctrine.orm.entity_manager"]
