<?php

namespace Explotic\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
//    public function findRoleLike($role){
//        $qb = $this->getEntityManager()->createQueryBuilder();
//        $qb ->select('u')
//            ->from('TransferMainBundle:User','u')
//            ->join('u.profil', 'p')
//            ->andWhere($qb->expr()->andX(                    
//                    $qb->expr()->like('u.roles', ':role'))   
//                    )                 
//            ->setParameter('role', '%'.$role.'%');
//            
//        return $qb;
//    }
}
