parameters:
#    explotic_admin.example.class: Explotic\AdminBundle\Example

services:
    explotic_admin.user:
        class: Explotic\AdminBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
          - { name: form.type, alias: explotic_user_registration }
    explotic_admin.user.access_control:
        class: Explotic\AdminBundle\Services\UserAccessControl
        arguments: ['@doctrine.orm.entity_manager','@security.context']
    explotic.user_manager:
        class: Explotic\AdminBundle\Services\ExploticUserManager
        arguments: ['@security.encoder_factory','@fos_user.util.username_canonicalizer','@fos_user.util.email_canonicalizer','@fos_user.entity_manager','%fos_user.model.user.class%']

        

        