parameters:
#    explotic_admin.example.class: Explotic\AdminBundle\Example

services:
    explotic_admin.user:
        class: Explotic\AdminBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
          - { name: form.type, alias: explotic_user_registration }
    explotic_admin.user.access_control:
        class: Explotic\AdminBundle\Services\UserAccessControl
        arguments: ['@doctrine.orm.entity_manager','@security.context']