parameters:
#    explotic_admin.example.class: Explotic\AdminBundle\Example

services:
#    explotic_admin.example:
#        class: %explotic_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
