#Explotic/AdminBundle/Resources/config/validation.yml
#Explotic\AdminBundle\Entity\User:
#  properties:
#    entreprise:
#      - 'Null': ~
#    recruteur:
#      - 'Null': ~
#    stagiaire:
#      - 'Null': ~
#    formateur:
#      - 'Null': ~
