Explotic\FormationBundle\Entity\Programme:
    type: entity
    table: programme
    repositoryClass: Explotic\FormationBundle\Entity\ProgrammeRepository
    manyToOne:
      module:
        targetEntity: Module
        inversedBy: programmes
      stagiaire:
        targetEntity: Explotic\TiersBundle\Entity\Stagiaire
        inversedBy: programmes
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        accompagnement:
          type: string
          length: 255
        FormationSalle:
          type: string
          length: 255
    lifecycleCallbacks: {  }
