Explotic\AdminBundle\Entity\User:
  type: entity
  table: fos_user
  manyToOne:
    entreprise:
      targetEntity: Explotic\TiersBundle\Entity\Entreprise
      inversedBy: comptes
      nullable: true
    recruteur:
      targetEntity: Explotic\TiersBundle\Entity\Recruteur
      inversedBy: comptes
      nullable: true
    stagiaire:
      targetEntity: Explotic\TiersBundle\Entity\Stagiaire
      inversedBy: comptes
      nullable: true
    formateur:
      targetEntity: Explotic\TiersBundle\Entity\Formateur
      inversedBy: comptes
      nullable: true
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
  lifecycleCallbacks: {  }
