Transfer\ProfilBundle\Entity\AgentDab:
  type: entity
  table: agentdab
  repositoryClass: Transfer\ProfilBundle\Entity\AgentDabRepository
  oneToOne:
      user:
        targetEntity: Transfer\MainBundle\Entity\User
        mappedBy: agentDab
  lifecycleCallbacks: {  }
