Transfer\ProfilBundle\Entity\Profil:
  type: entity
  table: profil
  repositoryClass: Transfer\ProfilBundle\Entity\ProfilRepository
  inheritanceType: SINGLE_TABLE
  discriminatorColumn:
    name: type
    type: string
    length: 255
  discriminatorMap:
    agentdab: AgentDab
    agenttrsp: AgentTrsp
    agentreception: AgentReception
  oneToOne:
    user:
      targetEntity: Transfer\MainBundle\Entity\User
      inversedBy: profil
      nullable: true
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    nom:
      type: string
      length: 255
    prenom:
      type: string
      length: 255
    courriel:
      type: string
      length: 255
    telephone:
      type: string
      length: 255
    dateEnregistrement:
      type: datetime
    dateModification:
      type: datetime
  lifecycleCallbacks:
    prePersist: [ setDateModification ]
