Explotic\AgendaBundle\Entity\Rdv:
    type: entity
    table: rdv
    repositoryClass: Explotic\AgendaBundle\Entity\RdvRepository
    manyToOne:
      creneauRdv:
        targetEntity: CreneauRdv
        inversedBy: Rdvs      
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        statutRdv:
            type: string       
    inheritanceType: JOINED
    discriminatorColumn:
      name: custom_rdv
      type: string
      length: 255
#    discriminatorMap:
#      mybooking : Explotic\PlanningBundle\Entity\MyBooking
    lifecycleCallbacks: {  }
