mon_profil:
    pattern:  /mon_profil
    defaults: { _controller: "ExploticMainBundle:Default:monProfil" }
    
mon_agenda:
    pattern:  /mon_agenda
    defaults: { _controller: "ExploticMainBundle:Default:monAgenda" }
    
homepage:
    pattern:  /
    defaults: { _controller: ExploticMainBundle:Default:index }