mon_profil:
    pattern:  /mon_profil
    defaults: { _controller: "ExploticMainBundle:Default:monProfil" }
    
homepage:
    pattern:  /
    defaults: { _controller: ExploticMainBundle:Default:index }