parameters:
#    transfer_profil.example.class: Transfer\ProfilBundle\Example

services:
    transfer_profil.acces:
        class: Transfer\ProfilBundle\Services\AccesProfil
        arguments: ["@security.context"]
