#explotic_agenda_homepage:
#    pattern:  /hello/{name}
#    defaults: { _controller: ExploticAgendaBundle:Default:index }

explotic_agenda_creneaumodele:
        resource: "@ExploticAgendaBundle/Resources/config/routing/creneaumodele.yml"
        prefix:   /priv/creneaumodele
        
explotic_agenda_creneaumodelegen:
        resource: "@ExploticAgendaBundle/Resources/config/routing/creneaumodelegen.yml"
        prefix:   /priv/creneaumodelegen

explotic_agenda_creneaurdvgen:
        resource: "@ExploticAgendaBundle/Resources/config/routing/creneaurdvgen.yml"
        prefix:   /priv/creneaurdvgen

explotic_agenda_creneaurdv:
        resource: "@ExploticAgendaBundle/Resources/config/routing/creneaurdv.yml"
        prefix:   /priv/creneaurdv
        
explotic_agenda_rdv:
        resource: "@ExploticAgendaBundle/Resources/config/routing/rdv.yml"
        prefix:   /priv/rdv

explotic_agenda_agenda:
        resource: "@ExploticAgendaBundle/Resources/config/routing/agenda.yml"
        prefix:   /priv/agenda
        
explotic_clean_all:
      pattern:  /clean
      defaults: { _controller: "ExploticAgendaBundle:default:cleanAgenda" }