<?php

namespace Explotic\FormationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InterventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterventionRepository extends EntityRepository
{
}
