<?php

namespace Explotic\AgendaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CreneauRdvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreneauRdvRepository extends EntityRepository
{
    public function findByPeriod($dateDebut, $dateFin){
        $query = $this->getEntityManager()->createQuery("
            SELECT cr
            FROM ExploticAgendaBundle:CreneauRdv cr
            WHERE cr.dateHeureDebut >= :debut
            AND cr.dateHeureFin <= :fin
            ORDER BY cr.dateHeureDebut
            ");
        $query->setParameters(array(
           'debut'=> $dateDebut,
            'fin'=> $dateFin
        ));
        return $query->getResult();
    }
}
