<?php

namespace Explotic\AgendaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RdvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RdvRepository extends EntityRepository
{
    public function findByPeriod($dateDebut, $dateFin,$calendrier){
        $query = $this->getEntityManager()->createQuery("
            SELECT r
            FROM ExploticAgendaBundle:Rdv r
            JOIN r.creneauRdv cr
            JOIN r.calendrier ca
            WHERE ca.id = :idca
            AND cr.dateHeureDebut >= :debut
            AND cr.dateHeureFin <= :fin            
            ORDER BY cr.dateHeureDebut
            ");
        $query->setParameters(array(
           'debut'=> $dateDebut,
            'fin'=> $dateFin,
            'idca'=> $calendrier->getId()
        ));
        return $query->getResult();
    }
}
