<?php

namespace Explotic\AgendaBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Explotic\AgendaBundle\Entity\Rdv;
/**
 * RdvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RdvRepository extends EntityRepository
{
    public function findByPeriod($dateDebut, $dateFin,$idCalendrier){
        $query = $this->getEntityManager()->createQuery("
            SELECT r
            FROM ExploticAgendaBundle:Rdv r
            JOIN r.creneauRdv cr
            JOIN r.calendrier ca
            WHERE ca.id = :idCal
            AND cr.dateHeureDebut >= :debut
            AND cr.dateHeureFin <= :fin            
            ORDER BY cr.dateHeureDebut
            ");
        $query->setParameters(array(
           'debut'=> $dateDebut,
            'fin'=> $dateFin,
            'idCal'=> $idCalendrier
        ));
        return $query->getResult();
    }
    
    public function findExists(Rdv $booking){
        $query = $this->getEntityManager()->createQuery('
            SELECT r
            FROM ExploticAgendaBundle:Rdv r
            JOIN r.creneauRdv cr
            JOIN r.agenda a           
            WHERE a.id = :agendaId
            AND cr.id = :creneauId
            ');
        $query->setParameters(array(
            'agendaId'=>$booking->getAgenda()->getId(),
            'creneauId'=>$booking->getCreneauRdv()->getId(),
        ));
        return $query->getResult();

    }

}
