<?php

namespace Explotic\AgendaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeRdvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeRdvRepository extends EntityRepository
{
}
