explotic_main_default:
    resource: "@ExploticMainBundle/Resources/config/routing/default.yml"
    prefix:   /priv
    
homepage:
    pattern:  /
    defaults: { _controller: ExploticMainBundle:Default:index }