parameters:
#    explotic_main.example.class: Explotic\MainBundle\Example

services:
#    explotic_main.example:
#        class: %explotic_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
