parameters:
    explotic_main.icopath.salle : bundles/exploticmain/images/school.png
    explotic_main.icopath.poste : bundles/exploticmain/images/forest2.png
    explotic_main.icopath.bureau : bundles/exploticmain/images/workoffice.png

services:
    form.type.gmaps_picker:
        class: Explotic\MainBundle\Form\Type\GMapsPickerType
        tags:
          - {name: form.type , alias : gmaps_picker }
    form.type.gmaps_address_picker:
        class: Explotic\MainBundle\Form\Type\GMapsAddressPickerType
        tags:
          - {name: form.type , alias : gmaps_address_picker }
    explotic_main.icopaths:
        class: Explotic\MainBundle\Model\icoPaths
        arguments: [%explotic_main.icopath.salle%,%explotic_main.icopath.poste%,%explotic_main.icopath.bureau%,'@service_container']